# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Squashed initial migration — full final schema.
#
# Data operations from the old chain were intentionally dropped: the RunPython
# payloads of 0002 (delete detached/duplicated StatusFromMagento rows) and 0003
# (deduplicate + backfill `attempts`) only clean up rows that predate the
# OneToOne/attempts schema — a fresh install has no rows, so they are no-ops here.
#
# Generated by Django 6.0.7 on 2026-07-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    replaces = [
        ("django_checkout_import_from_magento_api", "0001_initial"),
        ("django_checkout_import_from_magento_api", "0002_delete_duplicated"),
        ("django_checkout_import_from_magento_api", "0003_statusfrommagento_attempts"),
    ]

    dependencies = [
        ("django_checkout", "0001_squashed_0083_remove_paymentintent_one_intent_per_order_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusFromMagento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("magento_url", models.CharField(max_length=255)),
                (
                    "success",
                    models.BooleanField(default=False, help_text="Magento status in: ON_HOLD, CANCELED, COMPLETE]"),
                ),
                ("response", models.JSONField(null=True)),
                ("entity_id", models.CharField(blank=True, max_length=100, null=True)),
                ("increment_id", models.CharField(blank=True, max_length=100, null=True)),
                ("internal_message", models.CharField(blank=True, max_length=255, null=True)),
                ("attempts", models.PositiveIntegerField(default=0, help_text="Number of import attempts made")),
                (
                    "checkout_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_order_in_magento",
                        to="django_checkout.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status from Magento",
                "verbose_name_plural": "Statuses from Magento",
            },
        ),
    ]
